name: Build and Test (CMake + GoogleTest)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build

    - name: Create build directory
      run: cmake -E make_directory build

    - name: Configure CMake
      run: cmake -S . -B build -G Ninja -DCMAKE_CXX_STANDARD=20

    - name: Build
      run: cmake --build build

    - name: Run Tests
      working-directory: build
      run: ctest --output-on-failure
